#mapa sa imenom i simbolom valuta
mapa_valutaSVE = {
    "EUR": (('euro', 'Euro'), '€'),
    "AED": (('UAE dirham', 'United Arab Emirates dirham'), 'د.إ'),
    "AFN": (('afganistanski afgan', 'Afghan afghani'), '؋'),
    "ALL": (('albanski lek', 'Albanian lek'), 'L'),
    "AMD": (('armenski dram', 'Armenian dram'), '֏'),
    "ANG": (('nizozemskoantilski gulden', 'Netherlands Antillean guilder'), 'NAƒ'),
    "AOA": (('angolska kvanza', 'Angolan kwanza'), 'Kz'),
    "ARS": (('argentinski pezo', 'Argentine peso'), '$'),
    "AUD": (('australski dolar', 'Australian dollar'), 'AU$'),
    "AWG": (('arupski florin', 'Aruban florin'), 'Afl'),
    "AZN": (('azerbajdžanski manat', 'Azerbaijani manat'), '₼'),
    "BAM": (('konvertibilna marka', 'Bosnia and Herzegovina convertible mark'), 'KM'),
    "BBD": (('barbadoski dolar', 'Barbadian dollar'), 'BBD$'),
    "BDT": (('bangladeška taka', 'Bangladeshi taka'), '৳'),
    "BGN": (('bugarski lev', 'Bulgarian lev'), 'лв.'),
    "BHD": (('bahreinski dinar', 'Bahraini dinar'), '.د.ب'),
    "BIF": (('burundski franak', 'Burundian franc'), 'FBu'),
    "BMD": (('bermudski dolar', 'Bermudian dollar'), 'BD$'),
    "BND": (('brunejski dolar', 'Brunei dollar'), 'B$'),
    "BOB": (('bolivijski bolivijano', 'Bolivian boliviano'), 'Bs'),
    "BRL": (('brazilski real', 'Brazilian real'), 'R$'),
    "BSD": (('bahamski dolar', 'Bahamian dollar'), '$'),
    "BTN": (('butanski ngultrum', 'Bhutanese ngultrum'), 'Nu.'),
    "BWP": (('bocvanska pula', 'Botswana pula'), 'P'),
    "BYN": (('bjeloruski rubalj', 'Belarusian ruble'), 'Br'),
    "BZD": (('belizeanski dolar', 'Belize dollar'), 'BZ$'),
    "CAD": (('kanadski dolar', 'Canadian dollar'), 'CA$'),
    "CDF": (('kongoanski franak', 'Congolese franc'), 'FC'),
    "CHF": (('švicarski franak', 'Swiss franc'), 'CHF'),
    "CLP": (('čileanski pezo', 'Chilean peso'), 'CLP$'),
    "CNY": (('kineski renminbi juan', 'Renminbi'), '元'),
    "COP": (('kolumbijski pezo', 'Colombian peso'), 'COL$'),
    "CRC": (('kostarikanski kolon', 'Costa Rican colon'), '₡'),
    "CUP": (('kubanski pezo', 'Cuban peso'), '$'),
    "CVE": (('zelenortski eskudo', 'Cape Verdean escudo'), 'Esc'),
    "CZK": (('češka kruna', 'Czech koruna'), 'Kč'),
    "DJF": (('džibutski franak', 'Djiboutian franc'), 'Fdj'),
    "DKK": (('danska kruna', 'Danish krone'), 'kr.'),
    "DOP": (('dominikanski pezo', 'Dominican peso'), 'RD$'),
    "DZD": (('alžirski dinar', 'Algerian dinar'), 'دج'),
    "EGP": (('egipatska funta', 'Egyptian pound'), 'ج.م'),
    "ERN": (('eritrejska nakfa', 'Eritrean nakfa'), 'ናቕፋ'),
    "ETB": (('etiopski bir', 'Ethiopian birr'), 'ብር'),
    "FJD": (('fidžijski dolar', 'Fijian dollar'), 'FJ$'),
    "FKP": (('falklandska funta', 'Falkland Islands pound'), 'FK£'),
    "FOK": (('farska kruna', 'Faroese krona'), 'kr'),
    "GBP": (('britanska funta', 'Pound sterling'), '£'),
    "GEL": (('gruzijski lari', 'Georgian lari'), '₾'),
    "GGP": (('guernseyjska funta', 'Guernsey pound'), '£'),
    "GHS": (('ganski cedi', 'Ghanaian cedi'), 'GH₵'),
    "GIP": (('gibraltarska funta', 'Gibraltar pound'), '£'),
    "GMD": (('gambijski dalasi', 'Gambian dalasi'), 'D'),
    "GNF": (('gvinejski franak', 'Guinean franc'), 'FG'),
    "GTQ": (('gvatemalski kvecal', 'Guatemalan quetzal'), 'Q'),
    "GYD": (('gvajanski dolar', 'Guyanese dollar'), 'G$'),
    "HKD": (('hongkonški dolar', 'Hong Kong dollar'), '港元'),
    "HNL": (('honduraška lempira', 'Honduran lempira'), 'L'),
    "HRK": (('hrvatska kuna', 'Croatian kuna'), 'kn'),
    "HTG": (('haićanski gourd', 'Haitian gourde'), 'G'),
    "HUF": (('mađarska forinta', 'Hungarian forint'), 'Ft'),
    "IDR": (('indonezijska rupija', 'Indonesian rupiah'), 'Rp'),
    "ILS": (('novi izraelski šekel', 'Israeli shekel'), '₪'),
    "IMP": (('manska funta', 'Manx pound'), '£'),
    "INR": (('indijska rupija', 'Indian rupee'), '₹'),
    "IQD": (('irački dinar', 'Iraqi dinar'), 'د.ع'),
    "IRR": (('iranski rijal', 'Iranian rial'), '﷼'),
    "ISK": (('islandska kruna', 'Icelandic krona'), 'kr'),
    "JEP": (('jerseyjska funta', 'Jersey pound'), '£'),
    "JMD": (('jamajčanski dolar', 'Jamaican dollar'), 'J$'),
    "JOD": (('jordanski dinar', 'Jordanian dinar'), 'د.أ'),
    "JPY": (('japanski jen', 'Japanese yen'), '¥'),
    "KES": (('kenijski šiling', 'Kenyan shilling'), 'KSh'),
    "KGS": (('kirgiski som', 'Kyrgyzstani som'), 'сом'),
    "KHR": (('kambodžanski rijel', 'Cambodian riel'), '៛'),
    "KID": (('kiribatski dolar', 'Kiribati dollar'), '$'),
    "KMF": (('komorski franak', 'Comorian franc'), 'CF'),
    "KRW": (('južnokorejski von', 'South Korean won'), '₩'),
    "KWD": (('kuvajtski dinar', 'Kuwaiti dinar'), 'د.ك'),
    "KYD": (('kajmanski dolar', 'Cayman Islands dollar'), 'CI$'),
    "KZT": (('kazahstanski tenge', 'Kazakhstani tenge'), '₸'),
    "LAK": (('laoski kip', 'Lao kip'), '₭'),
    "LBP": (('libanonska funta', 'Lebanese pound'), 'ل.ل.'),
    "LKR": (('šrilanska rupija', 'Sri Lankan rupee'), 'රු'),
    "LRD": (('liberijski dolar', 'Liberian dollar'), 'L$'),
    "LSL": (('lesotski loti', 'Lesotho loti'), 'M'),
    "LYD": (('libijski dinar', 'Libyan dinar'), 'ل.د'),
    "MAD": (('marokanski dirham', 'Moroccan dirham'), 'د.م.'),
    "MDL": (('moldavski lej', 'Moldovan leu'), 'L'),
    "MGA": (('malgaški arijari', 'Malagasy ariary'), 'Ar'),
    "MKD": (('makedonski denar', 'Macedonian denar'), 'ден'),
    "MMK": (('mijanmarski kjat', 'Myanmar kyat'), 'K'),
    "MNT": (('mongolski tugrik', 'Mongolian tugrik'), '₮'),
    "MOP": (('makaonska pataka', 'Macau pataca'), 'MOP$'),
    "MRU": (('mauretanska ouguja', 'Mauritanian ouguiya'), 'UM'),
    "MUR": (('mauricijska rupija', 'Mauritian rupee'), '₨'),
    "MVR": (('maldivska rufija', 'Maldivian rufiyaa'), 'Rf.'),
    "MWK": (('malavijska kvača', 'Malawian kwacha'), 'K'),
    "MXN": (('meksički pezo', 'Mexican peso'), 'MX$'),
    "MYR": (('malezijski ringit', 'Malaysian ringgit'), 'RM'),
    "MZN": (('mozambički metikal', 'Mozambican metical'), 'MT'),
    "NAD": (('namibijski dolar', 'Namibian dollar'), 'N$'),
    "NGN": (('nigerijska naira', 'Nigerian naira'), '₦'),
    "NIO": (('nikaragvanska kordoba', 'Nicaraguan cordoba'), 'C$'),
    "NOK": (('norveška kruna', 'Norwegian krone'), 'kr'),
    "NPR": (('nepalska rupija', 'Nepalese rupee'), 'रु'),
    "NZD": (('novozelandski dolar', 'New Zealand dollar'), 'NZ$'),
    "OMR": (('omanski rijal', 'Omani rial'), 'ر.ع.'),
    "PAB": (('panamska balboa', 'Panamanian balboa'), 'B/.'),
    "PEN": (('peruanski novi sol', 'Peruvian sol'), 'S/'),
    "PGK": (('papuanska kina', 'Papua New Guinean kina'), 'K'),
    "PHP": (('filipinski pezo', 'Philippine peso'), '₱'),
    "PKR": (('pakistanska rupija', 'Pakistani rupee'), '₨.'),
    "PLN": (('poljski zloti', 'Polish zloty'), 'zł'),
    "PYG": (('paragvajski gvarani', 'Paraguayan guarani'), '₲'),
    "QAR": (('katarski rijal', 'Qatari riyal'), 'ر.ق'),
    "RON": (('rumunjski leu', 'Romanian leu'), 'L'),
    "RSD": (('srpski dinar', 'Serbian dinar'), 'дин.'),
    "RUB": (('ruski rubalj', 'Russian ruble'), '₽'),
    "RWF": (('ruandski franak', 'Rwandan franc'), 'FRw'),
    "SAR": (('saudijski rijal', 'Saudi riyal'), 'ر.س'),
    "SBD": (('salomonskootočni dolar', 'Solomon Islands dollar'), 'SI$'),
    "SCR": (('sejšelska rupija', 'Seychellois rupee'), 'SRe'),
    "SDG": (('sudanska funta', 'Sudanese pound'), 'ج.س'),
    "SEK": (('švedska kruna', 'Swedish krona'), 'kr'),
    "SGD": (('singapurski dolar', 'Singapore dollar'), 'S$'),
    "SHP": (('svetohelenska funta', 'Saint Helena pound'), '£'),
    "SLL": (('sijeraleonski leone', 'Sierra Leonean leone'), 'Le'),
    "SOS": (('somalijski šiling', 'Somali shilling'), 'Sh.So.'),
    "SRD": (('surinamski dolar', 'Surinamese dollar'), 'Sur$'),
    "SSP": (('južnosudanska funta', 'South Sudanese pound'), 'SS£'),
    "STN": (('saotomska dobra', 'São Tomé and Príncipe dobra'), 'Db'),
    "SYP": (('sirijska funta', 'Syrian pound'), 'ل.س'),
    "SZL": (('svazijski lilangeni', 'Swazi lilangeni'), 'E'),
    "THB": (('tajlandski baht', 'Thai baht'), '฿'),
    "TJS": (('tadžikistanski somoni', 'Tajikistani somoni'), 'SM'),
    "TMT": (('turkmenistanski manat', 'Turkmenistani manat'), 'T'),
    "TND": (('tuniski dinar', 'Tunisian dinar'), 'د.ت'),
    "TOP": (('tongaška pa\'anga', 'Tongan pa\'anga'), 'T$'),
    "TRY": (('turska lira', 'Turkish lira'), '₺'),
    "TTD": (('trinidadtobaški dolar', 'Trinidad and Tobago dollar'), 'TT$'),
    "TVD": (('tuvaluski dolar', 'Tuvaluan dollar'), 'TV$'),
    "TWD": (('novotajvanski dolar', 'New Taiwan dollar'), 'NT$'),
    "TZS": (('tanzanijski šiling', 'Tanzanian shilling'), 'TSh'),
    "UAH": (('ukrajinska hrivnja', 'Ukrainian hryvnia'), '₴'),
    "UGX": (('ugandski šiling', 'Ugandan shilling'), 'USh'),
    "USD": (('američki dolar', 'United States dollar'), '$'),
    "UYU": (('urugvajski pezo', 'Uruguayan peso'), '$U'),
    "UZS": (('uzbekistanski som', 'Uzbekistani so\'m'), 'сум'),
    "VES": (('venezuelanski bolivar', 'Venezuelan bolivar'), 'Bs.S.'),
    "VND": (('vijetnamski dong', 'Vietnamese dong'), '₫'),
    "VUV": (('vanuatski vatu', 'Vanuatu vatu'), 'VT'),
    "WST": (('samoanska tala', 'Samoan tala'), 'WS$'),
    "XAF": (('CFA franak BEAC', 'CFA franc'), 'FCFA'),
    "XCD": (('istočnokaripski dolar', 'Eastern Caribbean dollar'), 'EC$'),
    "XDR": (('posebna prava vučenja', 'Special drawing rights'), 'SDR'),
    "XOF": (('CFA franak BCEAO', 'CFA franc'), 'CFA'),
    "XPF": (('CFP franak', 'CFP franc'), '₣'),
    "YER": (('jemenski rijal', 'Yemeni rial'), 'ر.ي'),
    "ZAR": (('južnoafrički rand', 'South African rand'), 'R'),
    "ZMW": (('zambijska kvača', 'Zambian kwacha'), 'ZK'),
    "ZWL": (('zimbabveanski dolar', 'Zimbabwean dollar'), 'Z$')
}